#Header header 

int32 body_id
int32 tracking_status

float32 shoulder_l_abd
float32 shoulder_l_rot
float32 shoulder_l_flex
float32 elbow_l_flex
float32 elbow_l_rot
float32 wrist_l_flex

float32 shoulder_r_abd
float32 shoulder_r_rot
float32 shoulder_r_flex
float32 elbow_r_flex
float32 elbow_r_rot
float32 wrist_r_flex

float32 l_shoulder
float32 l_humerus
float32 l_ulna
float32 r_shoulder
float32 r_humerus
float32 r_ulna

geometry_msgs/Point32 tracking_error